/** IPC channel contracts between renderer and main. */
/** Invoke (request/response) channels. */
export const IpcChannels = {
    settingsGet: 'settings:get',
    settingsUpdate: 'settings:update',
    providersList: 'providers:list',
    providersSave: 'providers:save',
    providersRemove: 'providers:remove',
    providersDiscover: 'providers:discover',
    providersTest: 'providers:test',
    modelsList: 'models:list',
    modelPull: 'model:pull',
    modelLoad: 'model:load',
    modelUnload: 'model:unload',
    sessionsList: 'sessions:list',
    sessionCreate: 'session:create',
    sessionGet: 'session:get',
    sessionDelete: 'session:delete',
    chatSend: 'chat:send',
    chatAbort: 'chat:abort',
    toolApprove: 'tool:approve',
    contextPreview: 'context:preview',
    contextToggle: 'context:toggle',
    memoryList: 'memory:list',
    memorySave: 'memory:save',
    memoryDelete: 'memory:delete',
    workspaceList: 'workspace:list',
    workspaceAdd: 'workspace:add',
    workspaceRemove: 'workspace:remove',
    workspaceIndex: 'workspace:index',
    workspaceIndexStatus: 'workspace:indexStatus',
    workspaceSearch: 'workspace:search',
    workspaceFiles: 'workspace:files',
    connectorsList: 'connectors:list',
    connectorConnect: 'connector:connect',
    connectorDisconnect: 'connector:disconnect',
    connectorFetch: 'connector:fetch',
    guardrailsClassify: 'guardrails:classify',
    usageSummary: 'usage:summary',
    dialogOpenFolder: 'dialog:openFolder',
};
/** Push (main → renderer) channels. */
export const IpcEvents = {
    agentEvent: 'agent:event',
    indexProgress: 'index:progress',
};
//# sourceMappingURL=ipc.js.map